# Generated by Django 4.1.5 on 2023-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.CharField(max_length=4)),
                ("parecer", models.CharField(max_length=4)),
                ("situacao", models.CharField(max_length=80)),
                ("pj", models.CharField(max_length=80)),
                ("instituicao", models.CharField(max_length=200)),
                ("municipio", models.CharField(max_length=80)),
                ("data_solicitacao", models.CharField(max_length=80)),
                ("tipo_solicitacao", models.CharField(max_length=80)),
                ("nome_rt", models.CharField(max_length=80)),
                ("rt_tel", models.CharField(max_length=11)),
                ("rt_email", models.EmailField(max_length=100)),
                ("data_enc_presidencia", models.CharField(max_length=10)),
                ("data_rec_presidencia", models.CharField(max_length=10)),
                ("numero_art", models.CharField(max_length=4)),
                ("livro", models.CharField(max_length=3)),
                ("folha", models.CharField(max_length=4)),
                ("data_homologacao", models.CharField(max_length=10)),
                ("data_validade", models.CharField(max_length=10)),
            ],
        ),
    ]
