# Generated by Django 4.1.5 on 2023-01-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cliente",
            new_name="SolicitaRT",
        ),
    ]
