# Generated by Django 4.1.5 on 2023-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rts", "0002_rename_cliente_solicitart"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitart",
            name="cnpj",
            field=models.CharField(default="00000000000000", max_length=14),
        ),
    ]
